"""Khokhar & Son's Antivirus - Windows system tray icon.

Provides the spec section 43 tray integration:

    Open Dashboard / Quick Scan / Scan USB / Pause Protection /
    Settings / Exit

Implementation notes:

    - pystray is optional at runtime; :meth:`KhokharGuardTray.start`
      returns False (and the app falls back to normal close behaviour)
      when pystray or Pillow is unavailable.
    - Icons are loaded from bundled assets (assets/icons/*.png,
      generated by scripts/generate_icons.py). If the asset files are
      missing the module falls back to drawing the same shapes with
      Pillow, so the tray always works.
    - Icon states: green check = protected, amber pause bars =
      protection paused, red exclamation = warning (threat detected /
      protection error). A paused or warning state is always visible
      in the menu and tooltip (spec section 43: "If protection is
      paused, clearly display the security state").
    - While a scan runs the tray shows the protected shield with an
      alternating progress badge ("flash"): the app calls
      :meth:`set_scanning` on scan start/finish and the tray pulses
      the overlay until the scan ends, then restores the correct
      state icon. Paused/warning states take priority over the flash.
    - The icon runs on its own daemon thread; every callback marshals
      work onto the Tk UI thread through ``app.ui_call`` so widgets are
      never touched from the tray thread.
    - Windows notifications (spec section 41) are surfaced through the
      pystray icon (``icon.notify``) via :meth:`notify` - this works in
      the frozen build where PowerShell toast spawning is unreliable.
      Rate limiting and per-kind preferences stay in :mod:`utils.notify`.
"""

from __future__ import annotations

import threading
from pathlib import Path
from typing import TYPE_CHECKING, Any, Callable, List, Optional, Tuple

from utils import get_logger

if TYPE_CHECKING:  # pragma: no cover
    from ui.app import KhokharGuardApp

logger = get_logger("tray")

APP_TITLE = "Khokhar & Son's Antivirus"

# Asset locations: bundled data dir when frozen, repo when running
# from source.
_ASSET_DIR_NAME = Path("assets") / "icons"

# Palette for the drawn fallback icon (RGB) - mirrors theme + assets.
_GREEN = (34, 197, 94)
_AMBER = (245, 158, 11)
_RED = (239, 68, 68)
_BLUE = (59, 130, 246)
_OUTLINE = (30, 31, 36)
_MARK = (255, 255, 255)

# Logical tray states. STATE_SCANNING names the blue "working" shield
# asset; the live tray uses the flashing overlay instead (see below).
STATE_PROTECTED = "protected"
STATE_PAUSED = "paused"
STATE_WARNING = "warning"
STATE_SCANNING = "scanning"

# Seconds between flash frames while a scan is active.
DEFAULT_FLASH_INTERVAL = 0.6


def _icon_asset_dir() -> Path:
    """Directory holding the bundled tray icon assets."""
    try:
        from utils import paths

        return paths.bundled_data_dir() / _ASSET_DIR_NAME
    except Exception:  # noqa: BLE001 - fall back to repo-relative
        return Path(__file__).resolve().parent.parent / _ASSET_DIR_NAME


def _pystray_available() -> bool:
    """True when pystray and Pillow import cleanly."""
    try:
        import pystray  # noqa: F401
        from PIL import Image  # noqa: F401
    except Exception:  # noqa: BLE001 - optional dependency
        return False
    return True


def _load_state_icon(state: str) -> Optional["Any"]:
    """Load a state icon PNG from the bundled assets; None if absent."""
    try:
        from PIL import Image
    except Exception:  # noqa: BLE001
        return None
    asset = _icon_asset_dir() / f"tray_{state}.png"
    try:
        with Image.open(asset) as handle:
            return handle.convert("RGBA").copy()
    except OSError:
        return None


def _draw_shield(ok: Optional[bool] = None,
                 state: str = STATE_PROTECTED) -> "Any":
    """Render the tray shield with Pillow (fallback when assets miss).

    ``ok`` is honoured for backwards compatibility: True -> protected,
    False -> paused.
    """
    from PIL import Image, ImageDraw

    if ok is not None:
        state = STATE_PROTECTED if ok else STATE_PAUSED

    size = 64
    scale = 4
    big = size * scale
    image = Image.new("RGBA", (big, big), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)

    fill = {
        STATE_PROTECTED: _GREEN,
        STATE_PAUSED: _AMBER,
        STATE_WARNING: _RED,
        STATE_SCANNING: _BLUE,
    }.get(state, _GREEN)
    s = scale
    # Classic shield silhouette (same geometry as generate_icons.py).
    points = [
        (32 * s, 5 * s), (55 * s, 12 * s), (55 * s, 30 * s),
        (32 * s, 58 * s), (9 * s, 30 * s), (9 * s, 12 * s),
    ]
    draw.polygon(points, fill=fill + (255,), outline=_OUTLINE + (255,))

    if state == STATE_PAUSED:
        # Pause bars.
        draw.rectangle((23 * s, 22 * s, 29 * s, 42 * s), fill=_MARK + (255,))
        draw.rectangle((36 * s, 22 * s, 42 * s, 42 * s), fill=_MARK + (255,))
    elif state == STATE_WARNING:
        # Exclamation mark: bar + dot.
        draw.line([(32 * s, 20 * s), (32 * s, 37 * s)],
                  fill=_MARK + (255,), width=5 * s)
        draw.ellipse((29 * s, 41 * s, 35 * s, 47 * s), fill=_MARK + (255,))
    elif state == STATE_SCANNING:
        # Hollow ring: distinct from "paused" at small sizes.
        draw.ellipse((21 * s, 21 * s, 43 * s, 43 * s),
                     outline=_MARK + (255,), width=2 * s)
    else:
        # Check mark.
        draw.line([(20 * s, 31 * s), (29 * s, 40 * s), (45 * s, 22 * s)],
                  fill=_MARK + (255,), width=4 * s)

    return image.resize((size, size), Image.LANCZOS)


def _draw_scan_overlay(base: "Any", phase: int) -> "Any":
    """Composite the progress badge onto a copy of *base* (drawn path).

    Phase 0 renders a filled badge, phase 1 a hollow ring; alternating
    the two produces the visible pulse.
    """
    from PIL import ImageDraw

    image = base.copy().convert("RGBA")
    draw = ImageDraw.Draw(image)
    cx, cy, r = 46, 46, 10
    box = (cx - r, cy - r, cx + r, cy + r)
    if phase == 0:
        draw.ellipse(box, fill=_BLUE + (255,), outline=_MARK + (255,),
                     width=2)
        draw.line([(cx - 4, cy), (cx + 4, cy)], fill=_MARK + (255,), width=2)
    else:
        draw.ellipse(box, outline=_BLUE + (255,), width=3)
    return image


def state_icon(state: str) -> "Any":
    """Return the Pillow image for a tray state (assets, then drawn)."""
    image = _load_state_icon(state)
    if image is not None:
        return image
    return _draw_shield(state=state)


class KhokharGuardTray:
    """System tray icon bound to the running :class:`KhokharGuardApp`."""

    def __init__(self, app: "KhokharGuardApp",
                 flash_interval: float = DEFAULT_FLASH_INTERVAL) -> None:
        self.app = app
        self.flash_interval = max(0.05, float(flash_interval))
        self._icon: Any = None
        self._thread: Optional[threading.Thread] = None
        self._started = False
        self._state: str = STATE_PROTECTED

        # Scan progress hint ("flash") state.
        self._scan_active = False
        self._flash_stop = threading.Event()
        self._flash_thread: Optional[threading.Thread] = None

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    def start(self) -> bool:
        """Start the tray icon thread; False when unsupported."""
        if not _pystray_available():
            logger.info("System tray unavailable (pystray/Pillow missing)")
            return False

        import pystray

        if self._started:
            return True

        self._state = self._current_state()
        menu = pystray.Menu(self._menu_items)
        self._icon = pystray.Icon(
            "KhokharGuard", icon=state_icon(self._state), title=APP_TITLE,
            menu=menu,
        )

        def run_icon(icon: Any) -> None:
            """Run the pystray loop on its own thread."""
            try:
                icon.run(setup=self._on_ready)
            except Exception:  # noqa: BLE001 - tray must never kill the app
                logger.exception("Tray loop crashed")

        self._thread = threading.Thread(
            target=run_icon, args=(self._icon,), daemon=True,
            name="localguard-tray",
        )
        self._thread.start()
        self._started = True
        logger.info("System tray icon started")
        return True

    def stop(self) -> None:
        """Stop the tray icon (idempotent)."""
        self._stop_flash()
        icon = self._icon
        self._started = False
        self._icon = None
        if icon is not None:
            try:
                icon.stop()
            except Exception:  # noqa: BLE001
                logger.debug("Tray stop raised", exc_info=True)
        if self._thread is not None and self._thread is not threading.current_thread():
            self._thread.join(timeout=3)
        self._thread = None
        logger.info("System tray icon stopped")

    # ------------------------------------------------------------------
    # Scan progress hint
    # ------------------------------------------------------------------

    @property
    def is_scanning(self) -> bool:
        """True while the scan flash is active."""
        return self._scan_active

    def set_scanning(self, active: bool) -> None:
        """Start/stop the scan progress flash.

        Called by the app when a scan starts and when it finishes
        (completed, stopped, or failed). When *active* goes False the
        correct state icon is restored via :meth:`update_state`.
        """
        active = bool(active)
        if active == self._scan_active:
            if active:
                self.update_state()
            return
        self._scan_active = active
        if active:
            self._start_flash()
        else:
            self._stop_flash()
            self.update_state()
        logger.debug("Tray scan hint %s", "started" if active else "stopped")

    def _start_flash(self) -> None:
        """Launch the overlay flash loop (idempotent)."""
        if self._flash_thread is not None and self._flash_thread.is_alive():
            return
        self._flash_stop.clear()
        self._flash_thread = threading.Thread(
            target=self._flash_loop, daemon=True,
            name="localguard-tray-flash",
        )
        self._flash_thread.start()

    def _stop_flash(self) -> None:
        """Stop the flash loop and wait for it to exit."""
        self._flash_stop.set()
        thread = self._flash_thread
        self._flash_thread = None
        if thread is not None and thread is not threading.current_thread():
            thread.join(timeout=3)

    def _flash_loop(self) -> None:
        """Alternate the scan overlay until the scan ends.

        Runs on its own daemon thread. Each tick re-resolves the
        security state so paused/warning always override the hint.
        """
        phase = 0
        while not self._flash_stop.wait(self.flash_interval):
            icon = self._icon
            if icon is None or not self._started or not self._scan_active:
                break
            state = self._current_state()
            if state != STATE_PROTECTED:
                # Paused / warning outrank the progress hint.
                try:
                    icon.icon = state_icon(state)
                    icon.title = self._tooltip_for(state)
                except Exception:  # noqa: BLE001
                    logger.debug("Flash state override failed", exc_info=True)
                continue
            phase ^= 1
            try:
                icon.icon = self._scan_frame(phase)
                icon.title = self._scan_tooltip()
            except Exception:  # noqa: BLE001
                logger.debug("Flash frame update failed", exc_info=True)

    def _scan_frame(self, phase: int) -> "Any":
        """Icon for one flash phase (bundled overlay, then drawn)."""
        image = _load_state_icon(f"protected_overlay_{phase}")
        if image is not None:
            return image
        base = _load_state_icon(STATE_PROTECTED)
        if base is None:
            base = _draw_shield(state=STATE_PROTECTED)
        return _draw_scan_overlay(base, phase)

    def _scan_tooltip(self) -> str:
        """Tooltip while a scan runs, with a progress count if available."""
        progress: Optional[int] = None
        reader = getattr(self.app, "tray_scan_progress", None)
        if callable(reader):
            try:
                progress = reader()
            except Exception:  # noqa: BLE001
                progress = None
        if progress is None:
            return f"{APP_TITLE} - SCANNING..."
        return f"{APP_TITLE} - SCANNING ({progress:,} files)"

    # ------------------------------------------------------------------
    # State updates
    # ------------------------------------------------------------------

    def update_state(self) -> None:
        """Refresh icon/tooltip/menu to match the current security state."""
        icon = self._icon
        if icon is None:
            return

        def update() -> None:
            """Apply the refresh on the tray thread."""
            try:
                self._state = self._current_state()
                if self._scan_active and self._state == STATE_PROTECTED:
                    # The flash loop owns the icon while scanning; only
                    # keep the tooltip/menu fresh.
                    icon.title = self._scan_tooltip()
                else:
                    icon.icon = state_icon(self._state)
                    icon.title = self._tooltip_for(self._state)
                icon.update_menu()
            except Exception:  # noqa: BLE001
                logger.debug("Tray update failed", exc_info=True)

        threading.Thread(target=update, daemon=True,
                         name="localguard-tray-update").start()

    # ------------------------------------------------------------------
    # Notifications (spec section 41)
    # ------------------------------------------------------------------

    def notify(self, message: str, title: Optional[str] = None) -> bool:
        """Show a Windows notification through the tray icon.

        Safe to call from any thread (Win32 ``Shell_NotifyIcon`` is
        thread-safe and pystray's Win32 backend posts the balloon
        directly). Returns False when the tray is not running.
        Rate limiting and per-kind preferences are handled by
        :mod:`utils.notify`, not here.
        """
        icon = self._icon
        if icon is None or not self._started:
            return False
        try:
            icon.notify(message, title or APP_TITLE)
            return True
        except Exception:  # noqa: BLE001
            logger.debug("Tray notification failed", exc_info=True)
            return False

    # ------------------------------------------------------------------
    # State mapping
    # ------------------------------------------------------------------

    def _current_state(self) -> str:
        """Resolve the logical tray state from app + protection state."""
        protection = getattr(self.app, "protection", None)
        if protection is not None and getattr(protection, "paused", False):
            return STATE_PAUSED
        if callable(getattr(self.app, "tray_warning_active", None)):
            try:
                if self.app.tray_warning_active():
                    return STATE_WARNING
            except Exception:  # noqa: BLE001
                logger.debug("tray_warning_active callback failed",
                             exc_info=True)
        return STATE_PROTECTED

    @staticmethod
    def _tooltip_for(state: str) -> str:
        """Tooltip text for a state."""
        if state == STATE_PAUSED:
            return f"{APP_TITLE} - PROTECTION PAUSED"
        if state == STATE_WARNING:
            return f"{APP_TITLE} - ATTENTION REQUIRED"
        return APP_TITLE

    def _on_ready(self, icon: Any) -> None:
        """pystray setup callback: make the icon visible."""
        icon.visible = True

    # ------------------------------------------------------------------
    # Menu (spec section 43)
    # ------------------------------------------------------------------

    def _menu_items(self) -> Tuple[Any, ...]:
        """Build the dynamic menu; called by pystray on demand."""
        import pystray

        paused = bool(getattr(getattr(self.app, "protection", None),
                              "paused", False))
        return (
            pystray.MenuItem("Open Dashboard", self._on_open_dashboard,
                             default=True),
            pystray.Menu.SEPARATOR,
            pystray.MenuItem("Quick Scan", self._on_quick_scan),
            pystray.MenuItem("Scan USB", self._on_scan_usb),
            pystray.Menu.SEPARATOR,
            pystray.MenuItem(
                "Pause Protection", self._on_toggle_pause,
                checked=lambda item: paused, radio=True,
            ),
            pystray.Menu.SEPARATOR,
            pystray.MenuItem("Settings", self._on_settings),
            pystray.MenuItem("Exit", self._on_exit),
        )

    # ------------------------------------------------------------------
    # Actions (tray thread -> UI thread via app.ui_call)
    # ------------------------------------------------------------------

    def _on_open_dashboard(self, *args: Any) -> None:
        """Show the dashboard."""
        self.app.ui_call(self.app.show_window)

    def _on_quick_scan(self, *args: Any) -> None:
        """Start a quick scan from the tray."""
        self.app.ui_call(self.app.start_quick_scan)
        self.app.ui_call(self.app.show_window)

    def _on_scan_usb(self, *args: Any) -> None:
        """Open the USB protection page (drive choice is dynamic)."""
        self.app.ui_call(self.app.show_usb_page)
        self.app.ui_call(self.app.show_window)

    def _on_toggle_pause(self, *args: Any) -> None:
        """Pause/resume protection and refresh the tray state.

        Delegates to the app-level toggle, which targets the local
        protection stack or the background core depending on which is
        providing protection.
        """

        def toggle() -> None:
            """Run on the UI thread."""
            toggle_pause = getattr(self.app, "toggle_pause_protection", None)
            if callable(toggle_pause):
                toggle_pause()
            else:  # minimal stand-ins (tests): fall back to direct call
                if self.app.protection.paused:
                    self.app.protection.resume_protection()
                else:
                    self.app.protection.pause_protection()
            self.update_state()

        self.app.ui_call(toggle)

    def _on_settings(self, *args: Any) -> None:
        """Open the Settings page."""
        self.app.ui_call(lambda: self.app.show_page("settings"))
        self.app.ui_call(self.app.show_window)

    def _on_exit(self, *args: Any) -> None:
        """Exit the whole application from the tray."""
        self.app.ui_call(self.app.exit_application)


def create_tray(app: "KhokharGuardApp") -> Optional[KhokharGuardTray]:
    """Create and start a tray icon; None when unsupported.

    Never raises: tray failure must not prevent the GUI from running.
    """
    try:
        tray = KhokharGuardTray(app)
        if tray.start():
            return tray
    except Exception:  # noqa: BLE001
        logger.exception("Could not create system tray icon")
    return None
